version: "3.6"

services:
  postgres:
    env_file:
      - ".env"
    image: "postgres:11.6-alpine"
    volumes:
      - ./db/data:/var/lib/postgresql/data
  app:
    container_name: avril_app
    build: .
    ports:
      - "4000:4000"
    working_dir: /app
    depends_on:
      - postgres
    env_file:
      - ".env"
    command: iex -S mix phx.server
    volumes:
      - ".:/app"
    networks:
      - default
        # aliases:
        #   - phoenix
  nuxt:
    image: node:latest
    ports:
      - "3000:3000"
    working_dir: /app
    command: yarn setup
    env_file:
      - ".env"
    volumes:
      - "../Avril-Demat-Livret1:/app"
    networks:
      - default
