version: "3.6"

services:
  phoenix:
    build: .
    command: /app/scripts/init-phoenix.sh
    depends_on:
      - nginx
      - postgres
      - minio
    env_file:
      - ./.env
    healthcheck:
      test: /healthcheck_retry.sh curl -fsS localhost:4000/healthcheck
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 30s
    restart: always
    volumes:
      - .:/app
      - ./scripts/utils/healthcheck_retry.sh:/healthcheck_retry.sh
    working_dir: /app
  nginx:
    image: nginx:latest
    healthcheck:
      test: service nginx status
      timeout: 3s
      retries: 3
    ports:
      - ${NGINX_PORT:-80}:80
    restart: always
    volumes:
      - ./nginx/configs/${WHOST:-localhost}.conf:/etc/nginx/conf.d/default.conf
      - /var/log/nginx:/var/log/nginx
      - ./priv/static:/static
      - ./nginx/error_pages:/errors
  nuxt_booklet:
    command: yarn setup
    depends_on:
      - nginx
    env_file:
      - ./.env
    healthcheck:
      test: /healthcheck_retry.sh curl -fsS localhost:3000/healthcheck
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 1m
    image: node:16.17.0
    restart: always
    volumes:
      - ../avril-livret1:/app
      - ./scripts/utils/healthcheck_retry.sh:/healthcheck_retry.sh
    working_dir: /app
  nuxt_profile:
    command: yarn setup
    depends_on:
      - nginx
    env_file:
      - ./.env
    healthcheck:
      test: /healthcheck_retry.sh curl -fsS localhost:3000/healthcheck
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 1m
    image: node:16.17.0
    restart: always
    volumes:
      - ../avril-profil:/app
      - ./scripts/utils/healthcheck_retry.sh:/healthcheck_retry.sh
    working_dir: /app
  postgres:
    image: mdillon/postgis:11-alpine
    env_file:
      - ./.env
    healthcheck:
      test: pg_isready -U postgres
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 15s
    restart: always
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./scripts/init-postgres.sh:/docker-entrypoint-initdb.d/init-postgres.sh
      - ./db/dumps:/pg-dump
  minio:
    image: minio/minio
    command: server /data
    depends_on:
      - nginx
    env_file:
      - ./.env
    healthcheck:
      test: /healthcheck_retry.sh curl -fsS localhost:9000/minio/health/ready
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 1m
    restart: always
    volumes:
      - ./scripts/utils/healthcheck_retry.sh:/healthcheck_retry.sh

