version: "3.6"

services:
  app:
    image: avril_app
    command: /app/prod-server.sh
    deploy:
      replicas: 2
    ports:
      - "80:4000"
    depends_on:
      - init
  init:
    image: postgres:11.0-alpine
    command: /host/pg_restore.sh
    env_file:
      - ".env"
    volumes:
      - "./db:/host"
    depends_on:
      - postgres
    deploy:
      restart_policy:
        condition: none
        max_attempts: 1