version: "3.6"

services:
  app:
    image: avril_app
    command: /app/scripts/app.sh
    deploy:
      replicas: 2
      update_config:
        delay: 5s
        order: start-first
        parallelism: 1
        failure_action: rollback
      restart_policy:
        max_attempts: 10
        window: 1h
    depends_on:
      - front
      - pginit
      - postgres
  front:
    image: avril_app
    command: /app/scripts/front.sh
    env_file:
      - ".env"
    volumes:
      - ".:/app"
    deploy:
      restart_policy:
        condition: none
        max_attempts: 1
  pginit:
    image: avril_app
    command: /app/scripts/pginit.sh
    env_file:
      - ".env"
    volumes:
      - ".:/app"
    depends_on:
      - postgres
    deploy:
      restart_policy:
        condition: none
        max_attempts: 1
  compile:
    image: avril_app
    command: /app/scripts/compile.sh
    env_file:
      - ".env"
    volumes:
      - ".:/app"
    deploy:
      restart_policy:
        condition: none
        max_attempts: 1
  nginx:
    image: nginx:latest
    # command: nginx -g 'daemon off;'
    volumes:
      - "./nginx:/etc/nginx/conf.d"
      - "/var/log/nginx:/var/log/nginx"
    ports:
      - "80:80"
    deploy:
      restart_policy:
        delay: 10s
        # max_attempts: 3
        # window: 120s
    # healthcheck:
    #     test: wget -q0- http://avril_nuxt:3000
    #     interval: 5s
    #     timeout: 3s
    #     retries: 3
    depends_on:
      - app
      - nuxt