version: "3.6"

services:
  postgres:
    env_file:
      - ".env"
    image: "postgres:11.6-alpine"
    restart: always
    # volumes:
      # - pgdata:/var/lib/postgresql/data
      # - "/etc/postgresql:/etc/postgresql"
      # - "/var/log/postgresql:/var/log/postgresql"
      # - "/var/lib/postgresql:/var/lib/postgresql"
    healthcheck:
      test: pg_isready -U postgres
      interval: 15s
      timeout: 10s
      start_period: 15s
      retries: 2
  app:
    container_name: avril_app
    build: .
    ports:
      - "4000:4000"
    working_dir: /app
    depends_on:
      - postgres
      # - nuxt
    env_file:
      - ".env"
    command: iex -S mix phx.server
    volumes:
      - ".:/app"
    networks:
      default:
        aliases:
          - phoenix
  nuxt:
    image: node:latest
    ports:
      - "3000:3000"
    working_dir: /app
    # command: bash
    # command: yarn install && yarn build && yarn start
    env_file:
      - ".env"
    volumes:
      - "../Avril-Demat-Livret1:/app"
    networks:
      - default
    deploy:
      restart_policy:
        condition: none
        max_attempts: 1

# Define the volumes
# volumes:
#   pgdata:

# volumes:
#   postgres: {}
#   static:
#     driver_opts:
#       device: "tmpfs"
#       type: "tmpfs"
