version: "3.6"

services:
  phoenix:
    build: .
    command: /app/scripts/init-phoenix.sh
    depends_on:
      - postgres
      - minio
    env_file:
      - ./.env
    healthcheck:
      test: /healthcheck_retry.sh curl -fsS localhost:4000/healthcheck
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 30s
    volumes:
      - .:/app
      - ./scripts/utils/healthcheck_retry.sh:/healthcheck_retry.sh
    working_dir: /app
  nginx:
    depends_on:
      - phoenix
      - nuxt_booklet
      - nuxt_profile
      - minio
    image: nginx:latest
    healthcheck:
      test: service nginx status
      timeout: 3s
      retries: 3
    ports:
      - ${NGINX_PORT:-80}:80
    volumes:
      - ./nginx/${WHOST:-localhost}.conf:/etc/nginx/conf.d/default.conf
      - /var/log/nginx:/var/log/nginx
  nuxt_booklet:
    command: yarn setup
    env_file:
      - ./.env
    healthcheck:
      test: /healthcheck_retry.sh curl -fsS localhost:3000/healthcheck
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 1m
    image: node:latest
    volumes:
      - ../avril-livret1:/app
      - ./scripts/utils/healthcheck_retry.sh:/healthcheck_retry.sh
    working_dir: /app
  nuxt_profile:
    command: yarn setup
    env_file:
      - ./.env
    healthcheck:
      test: /healthcheck_retry.sh curl -fsS localhost:3000/healthcheck
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 1m
    image: node:latest
    volumes:
      - ../avril-profil:/app
      - ./scripts/utils/healthcheck_retry.sh:/healthcheck_retry.sh
    working_dir: /app
  postgres:
    env_file:
      - ./.env
    healthcheck:
      test: pg_isready -U postgres
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 15s
    image: postgres:11.6-alpine
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./scripts/init-postgres.sh:/docker-entrypoint-initdb.d/init-postgres.sh
      - ./db/dumps:/pg-dump
  minio:
    image: minio/minio
    command: server /data
    env_file:
      - ./.env
    healthcheck:
      test: /healthcheck_retry.sh curl -fsS localhost:9000/minio/health/ready
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 1m
    volumes:
      - ./scripts/utils/healthcheck_retry.sh:/healthcheck_retry.sh

