FROM avril_app

# Install all production dependencies
RUN mix deps.get --only prod

# Compile all dependencies
RUN mix deps.compile

# Copy all application files
COPY . .

# Compile the entire project and build the digest for production
RUN mix do compile, phx.digest
# RUN (cd deps/bcrypt_elixir && make clean && make)