version: "3.6"

services:
  phoenix:
    build: .
    command: /app/scripts/init-phoenix.sh
    depends_on:
      - postgres
    env_file:
      - ./.env
    healthcheck:
      test: /healthcheck_retry.sh 4000
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 30s
    volumes:
      - .:/app
      - /mnt/datalakepe/depuis_datalake/:/datalake
      - ./scripts/utils/healthcheck_retry.sh:/healthcheck_retry.sh
    working_dir: /app
  nginx:
    depends_on:
      - phoenix
      - nuxt
    image: nginx:latest
    healthcheck:
      test: service nginx status
      timeout: 3s
      retries: 3
    ports:
      - ${NGINX_PORT:-80}:80
    volumes:
      - ./nginx/${WHOST:-localhost}.conf:/etc/nginx/conf.d/default.conf
      - /var/log/nginx:/var/log/nginx
  nuxt:
    command: yarn setup
    env_file:
      - ./.env
    healthcheck:
      test: /healthcheck_retry.sh 3000
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 1m
    image: node:latest
    volumes:
      - ../avril-livret1:/app
      - ./scripts/utils/healthcheck_retry.sh:/healthcheck_retry.sh
    working_dir: /app
  postgres:
    env_file:
      - ./.env
    healthcheck:
      test: pg_isready -U postgres
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 15s
    image: postgres:11.6-alpine
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./scripts/init-postgres.sh:/docker-entrypoint-initdb.d/init-postgres.sh
      - ./db/dumps:/pg-dump
