version: "3.6"

services:
  app:
    image: avril_app
    command: /app/prod-server.sh
    deploy:
      replicas: 2
      update_config:
        delay: 5s
        order: start-first
        parallelism: 1
        failure_action: rollback
      restart_policy:
        max_attempts: 10
        window: 1h
    ports:
      - "80:4000"
    depends_on:
      - front
      - pginit
      - postgres
  front:
    image: avril_app
    command: npm install --prefix ./assets && npm run deploy --prefix ./assets && mix phx.digest
    volumes:
      - ".:/app"
  pginit:
    image: postgres:11.0-alpine
    command: /host/pg_restore.sh
    working_dir: /host
    env_file:
      - ".env"
    volumes:
      - "./db:/host"
    depends_on:
      - postgres
    deploy:
      restart_policy:
        condition: none
        max_attempts: 1