version: "3.6"

services:
  nginx:
    image: nginx:latest
    volumes:
      - "./nginx:/etc/nginx/sites-enabled"
      - "/var/log/nginx:/var/log/nginx"
    ports:
      - "80:80"
    depends_on:
      - app
  app:
    image: avril_app
    command: /app/scripts/app.sh
    deploy:
      replicas: 2
      update_config:
        delay: 5s
        order: start-first
        parallelism: 1
        failure_action: rollback
      restart_policy:
        max_attempts: 10
        window: 1h
    # ports:
    #   - "4000:4000"
    depends_on:
      - front
      - pginit
      - postgres
  front:
    image: avril_app
    command: /app/scripts/front.sh
    env_file:
      - ".env"
    volumes:
      - ".:/app"
    deploy:
      restart_policy:
        condition: none
        max_attempts: 1
  pginit:
    image: avril_app
    command: /app/scripts/pginit.sh
    env_file:
      - ".env"
    volumes:
      - ".:/app"
    depends_on:
      - postgres
    deploy:
      restart_policy:
        condition: none
        max_attempts: 1
  compile:
    image: avril_app
    command: /app/scripts/compile.sh
    env_file:
      - ".env"
    volumes:
      - ".:/app"
    deploy:
      restart_policy:
        condition: none
        max_attempts: 1