version: "3.6"

services:
  prod:
    build:
      context: ..
      dockerfile: Dockerfile.prod
    depends_on:
      - "app"
  avril:
    image: avril_prod
    command: /app/prod-server.sh
    deploy:
      replicas: 2
    depends_on:
      - postgres
