version: "3.6"

services:
  avril:
    image: avril_app
    command: /app/prod-server.sh
    working_dir: /app
    deploy:
      replicas: 2
    depends_on:
      - postgres
    ports:
      - "80:4000"
    volumes:
      - ".:/app"
