version: "3.6"

services:
  app:
    build: ..
    command: /app/scripts/app.sh
    # container_name: avril_app
    depends_on:
      - postgres
    env_file:
      - "../.env"
    volumes:
      - ..:/app
      # - /app/_build/
    working_dir: /app
  nginx:
    depends_on:
      - app
      - nuxt
    image: nginx:latest
    ports:
      - "${NGINX_PORT:-4000}:80"
    volumes:
      - "../nginx:/etc/nginx/conf.d"
      - "/var/log/nginx:/var/log/nginx"
  nuxt:
    image: node:latest
    working_dir: /app
    command: yarn setup
    env_file:
      - "../.env"
    volumes:
      - ../../avril-livret1:/app
      # - /app/.nuxt/
  postgres:
    env_file:
      - "../.env"
    image: "postgres:11.6-alpine"
    volumes:
      - "../db/data:/var/lib/postgresql/data"
      - "../scripts/pginit:/docker-entrypoint-initdb.d"
      - "../db/latest.dump:/pg-dump/latest.dump"
