version: "3.6"

services:
  postgres:
    env_file:
      - ../.env
    image: postgres:11.0-alpine
    volumes:
      - "/var/run/postgresql:/var/run/postgresql"
  avril:
    image: avril_prod
    command: /app/prod-server.sh
    deploy:
      replicas: 2
    ports:
      - "80:4000"

    depends_on:
      - postgres

volumes:
  postgres: {}
  static:
    driver_opts:
      device: "tmpfs"
      type: "tmpfs"
