version: "3.6"

services:
  postgres:
    image: "postgres:11.0-alpine"
    env_file:
      - "../.env"
    volumes:
      - "/var/run/postgresql:/var/run/postgresql"
  app:
    working_dir: /app
    depends_on:
      - "postgres"
    env_file:
      - "../.env"
    command: iex -S mix phx.server
    volumes:
      - "..:/app"

volumes:
  postgres: {}
  static:
    driver_opts:
      device: "tmpfs"
      type: "tmpfs"
